### ISSUE TITLE
taking gradients through the 'all' densenet

### ISSUE THREAD

**Issue by danbider** [mlmed/torchxrayvision#14]
Hi,

I am trying to plug your 'all' densenet (in eval mode + fixed weights) to my generative pipeline. However I'm getting errors taking gradients. I saw that you updated the package with the 'op' util we discussed here a couple of weeks ago; so I updated the package myself as well. Now I'm getting a different error, which is:

```
Warning: Error detected in AddBackward0. Traceback of forward call that caused the error:
  ...(some prints)...
  File "/home/ubuntu/DR-VAE/drvae/model/vae.py", line 233, in lossfun
    return vae_loss + disc_loss
 (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
File "/home/ubuntu/DR-VAE/drvae/model/train.py", line 297, in train_epoch_xraydata
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
**RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false) but got TensorOptions(dtype=float, device=cuda:0, layout=Strided, requires_grad=false) (validate_outputs at /pytorch/torch/csrc/autograd/engine.cpp:484)**
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fbd188b5536 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2d84224 (0x7fbd57f1e224 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x548 (0x7fbd57f1fd58 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7fbd57f21ce2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_init(int) + 0x39 (0x7fbd57f1a359 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7fbd646594d8 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xee0f (0x7fbd65246e0f in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x76ba (0x7fbd683996ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x6d (0x7fbd680cf41d in /lib/x86_64-linux-gnu/libc.so.6)
```
I'm not sure why it expects `cpu` there.

**Comment by ieee8023** [comment]
Do you have a small code sample I can run?

**Comment by ieee8023** [comment]
I made a toy example to compute grads on the GPU here: https://colab.research.google.com/drive/1cuBMBI_vzZofWN2XhjsA6ONBFfYZJcc9

**Comment by danbider** [comment]
Thanks for the example. So for you it seems to work? 
unfortunately on my end it's not a small code sample that I can copy and paste... it's a bit complicated at this stage with many modules etc. 
I'm loading your model like so
```
    # load discriminator, send to cuda, and set to eval mode (no dropout etc)
    discriminator = xrv.models.DenseNet(weights="all").cuda().eval()
    # freeze discriminator weights.
    for param in discriminator.parameters():
            param.requires_grad = False
```
and `discriminator` appears in the graph only in the `loss()` function. I have another trainable module (VAE) that precedes `discriminator`.
that's the [training script](https://github.com/danbider/DR-VAE/blob/master/train_xray.py
) that I'm running on AWS EC2 
and this is the loss [function](https://github.com/danbider/DR-VAE/blob/4f1df3101fac3cec3b00606fe55ab37821f72efa/drvae/model/vae.py#L198) where the action happens.
(i.e., a VAE with discriminative regularization).

**Comment by ieee8023** [comment]
So it was working before and then the op calibration update broke it? If so can you set `model.op_threshs = None` so it will skip that code?

**Comment by danbider** [comment]
With `model.op_threshs = None` it works; When `op_thresh` is executed, the problem is that it sends things to `cpu`.
So if I push data which is on `cuda:0` through the discrim model:
```
zdat = model.discrim_model[0](data)[:, model.dim_out_to_use]
print(data.device)
print(zdat.device)
```
results in
```
cuda:0
cpu
```

So it runs forward but no grads can be taken. It also naturally runs much slower with lower GPU usage. 
Suspicious points seem to be [this](https://github.com/mlmed/torchxrayvision/blob/835f9b5641145a626cc32b0b9dea7ba0a23b4c91/torchxrayvision/models.py#L182) definition of the `torch.zeros()` and [this](https://github.com/mlmed/torchxrayvision/blob/835f9b5641145a626cc32b0b9dea7ba0a23b4c91/torchxrayvision/models.py#L15) definition of `op_threshs` list. 

Let me know what you think!

**Comment by ieee8023** [comment]
Ok that was it. I just fixed it here: d6fc63e Thanks for finding that! Let me know if this fixed it.

**Comment by danbider** [comment]
Hi -- cool.
Now I tried to train including the `op_norm()` operation. Gradients can be computed now, but this makes the code intolerably slow (see below), reducing GPU usage from 65% to 1%.  
Here's my suggestion:

assuming 
```
model.op_threshs = None
op_threshs = [0.07422872, 0.038290843, 0.09814756, 0.0098118475, 0.023601074, 0.0022490358, 0.010060724, 0.103246614, 0.056810737, 0.026791653, 0.050318155, 0.023985857, 0.01939503, 0.042889766, 0.053369623, 0.035975814, 0.20204692, 0.05015312]
def op_norm(outputs, op_threshs):
    outputs_new = torch.zeros(outputs.shape, device = outputs.device)
    for i in range(len(outputs)):
        for t in range(len(outputs[0])):
            if (outputs[i,t]<op_threshs[t]):
                outputs_new[i,t] = outputs[i,t]/(op_threshs[t]*2) 
            else:
                outputs_new[i,t] = 1.0-((1.0-outputs[i,t])/((1.0-(op_threshs[t]))*2)) 
            
    return outputs_new
```
```
z = model(data_batch)
outputs = torch.sigmoid(z)

```
then we run the existing loop
```
import time
start_time = time.time()
outputs_orig = op_norm(outputs, op_threshs)
print (time.time()-start_time)
out: 1.9329781532287598
```
Instead I suggest a vectorized function as follows
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
op_threshs_arr = torch.tensor(np.asarray(op_threshs), 
                              dtype = torch.float).unsqueeze(0).expand(batch_size,-1).to(device)
```
```
def op_norm_new(outputs, op_threshs):
    
    outputs_new = torch.zeros(outputs.shape, device = outputs.device)
    mask_leq = outputs<op_threshs_arr
    outputs_new[mask_leq] = outputs[mask_leq]/(op_threshs_arr[mask_leq]*2)
    outputs_new[~mask_leq] = 1.0 - ((1.0 - outputs[~mask_leq])/((1-op_threshs_arr[~mask_leq])*2))
    
    return outputs_new
```
so if we run
```
start_time = time.time()
outputs_new = op_norm_new(outputs, op_threshs)
print(time.time()-start_time)
out: 0.0042896270751953125
```
and check 
```
(outputs_orig - outputs_new < 0.00001).detach().cpu().all()
out: tensor(True)
```
What do you think? 
I didn't do a pull request since i'm now just using the package not forking it.

**Comment by ieee8023** [comment]
Yes, you are right it should be vectorized. I wasn't thinking people would train with the calibration on.

This seems good but there must be a way to broadcast instead of needing to know the batch size. I can give it a try.

**Comment by danbider** [comment]
thanks! 
If you use the vectorized `op_norm` version suggested above, I think that one can simply broadcast again in each forward call using 

```
    def forward(self, x):
        features = self.features(x)
        out = F.relu(features, inplace=True)
        out = F.adaptive_avg_pool2d(out, (1, 1)).view(features.size(0), -1)
        out = self.classifier(out)
        
        if hasattr(self,"op_threshs") and (self.op_threshs != None):
            out = torch.sigmoid(out)
            out = op_norm(out, torch.tensor(np.asarray(self.op_threshs), 
                              dtype = torch.float).unsqueeze(0).expand(out.shape[0],out.shape[1]).to(device))
        return out
```

**Comment by ieee8023** [comment]
Do you want to make a pull request with it? Up to you if you want you get github credit for contributing!

**Comment by danbider** [comment]
You know what, let me try

**Comment by ieee8023** [comment]
Any update on the pull request? Otherwise I can do it.

**Comment by danbider** [comment]
Hi! thanks for the reminder. other things at home drew my attention (baby coming up this weekend), and I didn't fork and start a branch unfortunately, just cloned the repo.
Here's my version of `op_norm` which was tested in a few trained models. can just replace yours.
```
def op_norm(outputs, op_threshs_arr):
    """normalize outputs according to operating points for a given model.
    Args: 
        outputs: outputs of self.classifier(). torch.Size(batch_size, 16) 
        op_threshs_arr: torch.Size(batch_size, 16) with self.op_threshs expanded.
    Returns:
        outputs_new: normalized outputs, torch.Size(batch_size, 16)
    """
    outputs_new = torch.zeros(outputs.shape, device = outputs.device)
    mask_leq = outputs<op_threshs_arr
    outputs_new[mask_leq] = outputs[mask_leq]/(op_threshs_arr[mask_leq]*2)
    outputs_new[~mask_leq] = 1.0 - ((1.0 - outputs[~mask_leq])/((1-op_threshs_arr[~mask_leq])*2))
    
    return outputs_new
```

**Comment by ieee8023** [comment]
Closing this. Let me know if it wasn't resolved.
